[package]
name = "sirius"
description = "A tiny, experimental web engine"
version = "0.1.0"
license = "BSD-3-Clause"
kind = "Binary"
backend = "C"
binaries = ["balde", "sirius"]

[toolchain]
version = "2.2.0"

[dependencies]
pixie = ">= 6.1.0"
patty = ">= 0.3.5"
jsony = ">= 1.1.6"
"gh:elcritch/harfbuzzy" = ">= 0.2.2"
url = ">= 0.1.9"
colored_logger = ">= 0.1.0"
nimsimd = ">= 1.3.2"
chame = ">= 1.0.5"
shakar = ">= 0.1.3"
flatty = ">= 0.3.4"
"gh:planetis-m/vulkan" = ">= 1.4.344"
noise = ">= 0.1.10"
yaml = ">= 2.2.1"
results = ">= 0.5.1"
fuzzy = ">= 0.1.0"
surfer = ">= 0.2.5"
supersnappy = ">= 2.1.4"
sdfy = ">= 0.8.1"
variant = ">= 0.3.1"
curly = ">= 1.1.1"
bumpy = ">= 1.1.3"
chronicles = ">= 0.12.3"
vmath = ">= 3.0.0"
stack_strings = ">= 1.1.4"
stylus = ">= 0.1.5"
"gh:ferus-web/nim-gmp" = ">= 0.1.0"
opengl = ">= 1.2.9"
chroma = ">= 1.0.0"
nint128 = ">= 0.3.3"

[platforms.native]
include = ["vulkan", "wayland-egl", "libcurl", "fontconfig", "wayland-client", "wayland-egl-backend", "glesv2", "egl", "simdutf"]
link = ["vulkan", "wayland-egl", "libcurl", "fontconfig", "wayland-client", "wayland-egl-backend", "glesv2", "egl", "simdutf"]
